version: '3.1'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "3333:3333"
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bookstore
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge